# Generated by Django 4.2.18 on 2025-10-01 17:40

import apps.students.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[apps.students.utils.valid_phone],
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[apps.students.utils.valid_phone],
                        verbose_name="whatsapp",
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
            },
        ),
        migrations.CreateModel(
            name="ClientStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Статус клиента",
                "verbose_name_plural": "Статусы клиентов",
            },
        ),
        migrations.CreateModel(
            name="TrailLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trail_lesson_branch",
                        to="branches.branch",
                    ),
                ),
                (
                    "directions",
                    models.ManyToManyField(
                        related_name="trail_lesson_dirs",
                        to="branches.direction",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "mentors",
                    models.ManyToManyField(
                        related_name="trail_lesson_mentors", to="mainapp.mentor"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пробный урок",
                "verbose_name_plural": "Пробные уроки",
            },
        ),
    ]
