# Generated by Django 4.2.18 on 2025-10-01 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traillesson",
            name="recruiter",
            field=models.ManyToManyField(
                related_name="trail_lesson_recruiter", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="recruiter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_recruiter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_status",
                to="sales.clientstatus",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="trail_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_trail_lesson",
                to="sales.traillesson",
            ),
        ),
    ]
