# Generated by Django 4.2.18 on 2025-10-01 17:40

import apps.students.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.TextField(blank=True, help_text="не обязательно", null=True),
                ),
                (
                    "receipt",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
            ],
            options={
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплаты",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "start_mount",
                    models.IntegerField(
                        default=1,
                        help_text="по умолчанию 1",
                        validators=[apps.students.utils.validate_positive],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Обязательное поле", max_length=254, unique=True
                    ),
                ),
                (
                    "discount",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="по умолчанию 0",
                        null=True,
                        verbose_name="Скидка в Процентрах",
                    ),
                ),
                (
                    "discount_of_cash",
                    models.FloatField(
                        blank=True,
                        default=0,
                        help_text="по умолчанию 0",
                        null=True,
                        verbose_name="сумма скидки",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="не обязательно, при записи введите номер в международном формате",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="не обязательно, при записи введите номер в международном формате",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        help_text="не обязательно",
                        max_length=255,
                        null=True,
                        verbose_name="Телеграм",
                    ),
                ),
                (
                    "studies",
                    models.BooleanField(
                        default=True, verbose_name="Учится в настоящее время"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, help_text="не обязательно", null=True),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.BooleanField(default=False, verbose_name="Договор"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_course",
                        to="mainapp.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
                "ordering": ["-studies", "-create_at"],
            },
        ),
    ]
