# Generated by Django 4.2.18 on 2025-10-01 17:40

import apps.students.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Обязательное поле", max_length=254, unique=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[apps.students.utils.valid_phone],
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[apps.students.utils.valid_telegram],
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="branches.branch",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mentor_dir",
                        to="branches.direction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ментор",
                "verbose_name_plural": "Менторы",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notified", models.BooleanField(auto_created=True, default=False)),
                ("title", models.CharField(max_length=100)),
                ("date_start", models.DateField(verbose_name="Старт группы")),
                ("time_start", models.TimeField(verbose_name="Начало занятий")),
                ("time_end", models.TimeField(verbose_name="Конец занятий")),
                (
                    "telegram_group_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на группу телеграм"
                    ),
                ),
                (
                    "course_duration",
                    models.PositiveIntegerField(
                        verbose_name="Длительность курса в месяцах"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=9, verbose_name="Цена за месяц"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="branches.branch",
                    ),
                ),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_dir",
                        to="branches.direction",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_mentor",
                        to="mainapp.mentor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "ordering": ["-date_start"],
            },
        ),
    ]
