# Generated by Django 4.2.18 on 2025-10-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
            },
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("opening_date", models.DateField()),
                ("instagram", models.URLField(blank=True, max_length=255, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=255, null=True)),
                ("currency", models.CharField(default="KZT", max_length=10)),
                ("chat_id", models.CharField(max_length=25, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "organization",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование организации",
                    ),
                ),
                (
                    "bik",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="БИК"
                    ),
                ),
                (
                    "bin",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="БИН"
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Счет"
                    ),
                ),
                (
                    "director_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Директор"
                    ),
                ),
                (
                    "stamp",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="stamps/",
                        verbose_name="Печать",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_country",
                        to="branches.country",
                    ),
                ),
                (
                    "list_direction",
                    models.ManyToManyField(
                        related_name="directions_branch", to="branches.direction"
                    ),
                ),
            ],
            options={
                "verbose_name": "Филиал",
                "verbose_name_plural": "Филиалы",
            },
        ),
    ]
